"""
devmode/session.py — Developer Mode session engine
===================================================
Runs the role-driven SDLC phases (devmode/phases.py), each as a full
back-and-forth discussion that produces an editable artifact. State is persisted
to docs/dev/state.json so a design can be paused and resumed, and any phase can
be revisited to change a decision.
"""

from __future__ import annotations

import datetime
import json
import sys
from pathlib import Path

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.rule import Rule

from devmode.phases import PHASES, PHASES_BY_ID, PhaseSpec

console = Console()

_STATUS_ICON = {"done": "✅", "skipped": "⏭", "in_progress": "🔄", "pending": "○"}


def _stream(messages, precise: bool = False) -> str:
    """Stream a conversational model response to the terminal; return the text."""
    from core.model import get_chat_model

    llm = get_chat_model(precise=precise)
    acc = ""
    console.print()
    try:
        for chunk in llm.stream(messages):
            piece = chunk.content
            if isinstance(piece, str) and piece:
                acc += piece
                sys.stdout.write(piece)
                sys.stdout.flush()
    except Exception as e:  # noqa: BLE001
        console.print(f"\n[red]⚠ Model error: {e}[/red]")
        return acc
    sys.stdout.write("\n")
    return acc


class DevSession:
    """Orchestrates the SDLC design phases for a project."""

    def __init__(self, workspace: Path, idea: str | None = None):
        self.workspace = workspace.resolve()
        self.dir = self.workspace / "docs" / "dev"
        self.state_file = self.dir / "state.json"
        self.state = self._load_or_init(idea)

    # ── State ──────────────────────────────────────────────────────────────────

    def _load_or_init(self, idea: str | None) -> dict:
        if self.state_file.exists():
            try:
                state = json.loads(self.state_file.read_text(encoding="utf-8"))
                if idea:
                    console.print("[dim]A Developer Mode session already exists here — "
                                  "resuming it. (Delete docs/dev to start over.)[/dim]")
                return state
            except Exception:
                pass
        return {
            "idea": idea or "",
            "created_at": datetime.datetime.now().isoformat(timespec="seconds"),
            "phases": {p.id: {"title": p.title, "status": "pending"} for p in PHASES},
        }

    def _save(self) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        self.state["updated_at"] = datetime.datetime.now().isoformat(timespec="seconds")
        self.state_file.write_text(json.dumps(self.state, indent=2, ensure_ascii=False),
                                   encoding="utf-8")

    def _set_status(self, phase_id: str, status: str) -> None:
        self.state["phases"][phase_id]["status"] = status
        self._save()

    def has_session(self) -> bool:
        return self.state_file.exists()

    # ── Artifacts ──────────────────────────────────────────────────────────────

    def _artifact_path(self, spec: PhaseSpec) -> Path:
        return (self.workspace / spec.filename) if spec.target == "conventions" \
            else (self.dir / spec.filename)

    def _prior_artifacts(self) -> str:
        """Concatenate completed doc artifacts to ground later phases."""
        parts = []
        for p in PHASES:
            if p.target != "doc":
                continue
            path = self.dir / p.filename
            if path.exists():
                parts.append(path.read_text(encoding="utf-8", errors="replace"))
        return "\n\n---\n\n".join(parts)

    def _write_artifact(self, spec: PhaseSpec, decision: str, transcript: str) -> Path:
        path = self._artifact_path(spec)
        path.parent.mkdir(parents=True, exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        if spec.target == "conventions":
            content = (f"# AICODER.md — project conventions\n_Generated by Developer Mode: {ts}_\n\n"
                       f"{decision}\n")
        else:
            content = (f"# {spec.title}\n_Decided: {ts}_\n\n## Decision\n\n{decision}\n\n"
                       f"---\n\n<details><summary>Discussion</summary>\n\n{transcript}\n\n</details>\n")
        path.write_text(content, encoding="utf-8")
        return path

    # ── Discussion ─────────────────────────────────────────────────────────────

    def _system_prompt(self, spec: PhaseSpec, context: str, research: str) -> str:
        parts = [
            f"You are a {spec.role} helping an experienced developer design a software "
            f"project, one SDLC phase at a time. This phase: {spec.title}.",
            f"Project idea: {self.state.get('idea') or '(see prior decisions)'}",
            f"Your goal: {spec.goal} Specifically decide: {spec.focus}.",
            "Be concrete and senior: propose a clear recommendation with brief rationale, "
            "ask focused questions only where you genuinely need the developer's decision, "
            "and adapt to their answers. Keep it tight — they are experienced.",
        ]
        if context:
            parts += ["", "# Decisions already made in earlier phases", context]
        if research:
            parts += ["", "# Current information from the web (use for versions/best practices)", research]
        return "\n".join(parts)

    def _research(self, spec: PhaseSpec) -> str:
        try:
            from rag.research import research_topic
            topic = f"{self.state.get('idea','')} {spec.title} best practices current versions 2026"
            return research_topic(topic, project="")["text"][:3000]
        except Exception:
            return ""

    def _discuss(self, spec: PhaseSpec) -> tuple[str, list]:
        context = self._prior_artifacts()
        research = self._research(spec) if spec.research else ""
        if spec.research:
            console.print("[dim]🌐 Researching current best practices…[/dim]")

        system = self._system_prompt(spec, context, research)
        opening = (f"Open the {spec.title} phase: give a concise first-draft proposal for "
                   f"{spec.focus}, then ask me the key questions you need answered.")
        messages = [SystemMessage(content=system), HumanMessage(content=opening)]

        console.print(Rule(f"[bold magenta]{spec.role} — {spec.title}[/bold magenta]"))
        ai = _stream(messages)
        messages.append(AIMessage(content=ai))
        transcript = [f"**{spec.role}:** {ai}"]

        while True:
            console.print("\n[dim]Reply, or type: [bold]done[/bold] · [bold]skip[/bold] · "
                          "[bold]revise[/bold] · [bold]pause[/bold][/dim]")
            try:
                user = Prompt.ask(f"[bold yellow]{spec.id}[/bold yellow]").strip()
            except (EOFError, KeyboardInterrupt):
                return "pause", messages
            if not user:
                continue
            cmd = user.lower()
            if cmd in ("done", "d"):
                return "done", messages
            if cmd in ("skip", "s"):
                return "skip", messages
            if cmd in ("revise", "r"):
                return "revise", messages
            if cmd in ("pause", "p"):
                return "pause", messages
            messages.append(HumanMessage(content=user))
            transcript.append(f"**You:** {user}")
            ai = _stream(messages)
            messages.append(AIMessage(content=ai))
            transcript.append(f"**{spec.role}:** {ai}")
        # (unreachable) transcript joined by caller via _last_transcript

    def _summarize(self, spec: PhaseSpec, messages: list) -> str:
        prompt = (
            f"Summarize this {spec.title} discussion into a clean, structured Markdown "
            f"record of the DECISIONS made about: {spec.focus}. Use headings, bullets, and "
            f"tables where useful. This is the permanent spec for this phase — be precise "
            f"and complete, no fluff."
        )
        out = _stream(list(messages) + [HumanMessage(content=prompt)], precise=True)
        return out.strip()

    # ── Phase runner ───────────────────────────────────────────────────────────

    def _run_phase(self, spec: PhaseSpec) -> str:
        while True:  # retry loop for 'revise'
            transcript_msgs: list = []
            result, messages = self._discuss(spec)
            if result in ("pause", "skip"):
                return result
            if result == "revise":
                console.print("[dim]Restarting this phase…[/dim]")
                continue
            # result == "done" → summarize + write artifact
            console.print(Rule("[dim]📝 Capturing decision…[/dim]"))
            decision = self._summarize(spec, messages)
            transcript = "\n\n".join(
                (f"**You:** {m.content}" if isinstance(m, HumanMessage) else f"**{spec.role}:** {m.content}")
                for m in messages[2:]  # skip system + opening
            )
            path = self._write_artifact(spec, decision, transcript)
            console.print(f"  [green]✔[/green] Saved → [bold]{path.relative_to(self.workspace)}[/bold]")
            return "done"

    # ── Public ─────────────────────────────────────────────────────────────────

    def show_status(self) -> None:
        lines = []
        for p in PHASES:
            st = self.state["phases"].get(p.id, {}).get("status", "pending")
            lines.append(f"  {_STATUS_ICON.get(st, '○')}  {p.title}")
        console.print(Panel("\n".join(lines),
                            title=f"[bold magenta]🧭 Developer Mode — {self.state.get('idea','')[:50]}[/bold magenta]",
                            subtitle="[dim]docs/dev/[/dim]", border_style="magenta"))

    def run(self, resume: bool = False, only: str | None = None) -> None:
        if not self.state.get("idea") and not resume:
            console.print("[yellow]No idea set. Use: develop <your idea>[/yellow]")
            return
        self._save()
        self.show_status()

        specs = [PHASES_BY_ID[only]] if only and only in PHASES_BY_ID else PHASES
        for spec in specs:
            st = self.state["phases"][spec.id]["status"]
            if st == "done" and not only:
                continue
            console.print()
            if st != "in_progress" and not Confirm.ask(
                f"[bold]Run phase: {spec.title}?[/bold] [dim]({spec.role})[/dim]", default=True
            ):
                self._set_status(spec.id, "skipped")
                continue
            self._set_status(spec.id, "in_progress")
            result = self._run_phase(spec)
            if result == "pause":
                console.print("\n[yellow]Paused. Resume with [bold]dev resume[/bold].[/yellow]")
                self._set_status(spec.id, "pending")
                return
            self._set_status(spec.id, "skipped" if result == "skip" else "done")
            self.show_status()

        console.print()
        console.print(Panel(
            "🎉 Design phases complete.\n\n"
            "[dim]Artifacts are in docs/dev/ and conventions in AICODER.md — edit them "
            "anytime. Next: the build hand-off (coming next).[/dim]",
            title="[bold green]Developer Mode — design done[/bold green]", border_style="green"))
