"""
devmode/session.py — Developer Mode session engine
===================================================
Runs the role-driven SDLC phases (devmode/phases.py), each as a full
back-and-forth discussion that produces an editable artifact. State is persisted
to docs/dev/state.json so a design can be paused and resumed, and any phase can
be revisited to change a decision.
"""

from __future__ import annotations

import datetime
import json
import sys
from pathlib import Path

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.rule import Rule

from devmode.phases import PHASES, PHASES_BY_ID, PhaseSpec

console = Console()

_STATUS_ICON = {"done": "✅", "skipped": "⏭", "in_progress": "🔄", "pending": "○"}


def _decision_section(text: str) -> str:
    """Extract the '## Decision' body of an artifact (or the whole text)."""
    import re
    m = re.search(r"## Decision\s*\n+(.*?)\n+---", text, re.DOTALL)
    return m.group(1).strip() if m else text.strip()


def _stream(messages, precise: bool = False) -> str:
    """Stream a conversational model response to the terminal; return the text."""
    from core.model import get_chat_model

    llm = get_chat_model(precise=precise)
    acc = ""
    console.print()
    try:
        for chunk in llm.stream(messages):
            piece = chunk.content
            if isinstance(piece, str) and piece:
                acc += piece
                sys.stdout.write(piece)
                sys.stdout.flush()
    except Exception as e:  # noqa: BLE001
        console.print(f"\n[red]⚠ Model error: {e}[/red]")
        return acc
    sys.stdout.write("\n")
    return acc


class DevSession:
    """Orchestrates the SDLC design phases for a project."""

    def __init__(self, workspace: Path, idea: str | None = None):
        self.workspace = workspace.resolve()
        self.dir = self.workspace / "docs" / "dev"
        self.state_file = self.dir / "state.json"
        self.state = self._load_or_init(idea)

    # ── State ──────────────────────────────────────────────────────────────────

    def _load_or_init(self, idea: str | None) -> dict:
        if self.state_file.exists():
            try:
                state = json.loads(self.state_file.read_text(encoding="utf-8"))
                if idea:
                    console.print("[dim]A Developer Mode session already exists here — "
                                  "resuming it. (Delete docs/dev to start over.)[/dim]")
                return state
            except Exception:
                pass
        return {
            "idea": idea or "",
            "created_at": datetime.datetime.now().isoformat(timespec="seconds"),
            "phases": {p.id: {"title": p.title, "status": "pending"} for p in PHASES},
        }

    def _save(self) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        self.state["updated_at"] = datetime.datetime.now().isoformat(timespec="seconds")
        self.state_file.write_text(json.dumps(self.state, indent=2, ensure_ascii=False),
                                   encoding="utf-8")

    def _set_status(self, phase_id: str, status: str) -> None:
        self.state["phases"][phase_id]["status"] = status
        self._save()

    def has_session(self) -> bool:
        return self.state_file.exists()

    # ── Artifacts ──────────────────────────────────────────────────────────────

    def _artifact_path(self, spec: PhaseSpec) -> Path:
        return (self.workspace / spec.filename) if spec.target == "conventions" \
            else (self.dir / spec.filename)

    def _prior_artifacts(self) -> str:
        """Concatenate completed decision artifacts to ground later phases."""
        parts = []
        for p in PHASES:
            if p.target != "doc" or p.kind == "review":
                continue
            path = self.dir / p.filename
            if path.exists():
                parts.append(path.read_text(encoding="utf-8", errors="replace"))
        return "\n\n---\n\n".join(parts)

    def _write_artifact(self, spec: PhaseSpec, decision: str, transcript: str) -> Path:
        path = self._artifact_path(spec)
        path.parent.mkdir(parents=True, exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        if spec.target == "conventions":
            content = (f"# AICODER.md — project conventions\n_Generated by Developer Mode: {ts}_\n\n"
                       f"{decision}\n")
        else:
            content = (f"# {spec.title}\n_Decided: {ts}_\n\n## Decision\n\n{decision}\n\n"
                       f"---\n\n<details><summary>Discussion</summary>\n\n{transcript}\n\n</details>\n")
        path.write_text(content, encoding="utf-8")
        return path

    # ── Discussion ─────────────────────────────────────────────────────────────

    # ── Existing-codebase awareness (brownfield) ───────────────────────────────

    _CODE_EXTS = {".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java",
                  ".rb", ".vue", ".php", ".cs", ".cpp", ".c", ".kt", ".swift"}
    _SKIP_NAMES = {"AICODER.md", "README.md", "CHANGELOG.md", "LICENSE"}

    def _iter_source_files(self):
        from core.config import get_config
        ignore = set(get_config().ignore_dirs)
        for p in sorted(self.workspace.rglob("*")):
            if not p.is_file() or any(part in ignore for part in p.parts):
                continue
            rel = p.relative_to(self.workspace)
            if rel.parts[:2] == ("docs", "dev") or p.name in self._SKIP_NAMES:
                continue
            if p.suffix.lower() in self._CODE_EXTS:
                yield p, rel

    def _has_existing_code(self) -> bool:
        return next(self._iter_source_files(), None) is not None

    def _repo_overview(self) -> str:
        if getattr(self, "_overview_cache", None) is None:
            try:
                from core.context import WorkspaceContext
                self._overview_cache = WorkspaceContext(self.workspace).overview()
            except Exception:
                self._overview_cache = ""
        return self._overview_cache

    def _sample_code(self, max_files: int = 5, max_chars: int = 1200) -> str:
        samples, n = [], 0
        for p, rel in self._iter_source_files():
            if n >= max_files:
                break
            try:
                samples.append(f"=== {rel} ===\n" + p.read_text(encoding="utf-8", errors="replace")[:max_chars])
                n += 1
            except Exception:
                continue
        return "\n\n".join(samples)

    def _relevant_docs(self) -> str:
        try:
            from core.config import project_id
            from rag.store import KnowledgeBase
            hits = KnowledgeBase.get().search(self.state.get("idea", ""), n=3,
                                              max_distance=0.8, project=project_id(self.workspace))
            return ("\n\n".join(h["content"] for h in hits))[:2000] if hits else ""
        except Exception:
            return ""

    def _infer_conventions(self) -> str:
        samples = self._sample_code()
        if not samples.strip():
            return ""
        system = (
            "You are a Tech Lead. Infer the project's EXISTING coding conventions from its "
            "structure and sample files: folder layout, file naming, function/variable naming, "
            "formatting, error-handling/logging patterns, docstring/comment style, and test "
            "layout. Output a concise, concrete summary of the conventions already in use."
        )
        prompt = f"# Repo overview\n{self._repo_overview()}\n\n# Sample files\n{samples}\n\nInfer the conventions."
        try:
            from core.model import get_chat_model
            ai = get_chat_model(precise=True).invoke(
                [SystemMessage(content=system), HumanMessage(content=prompt)])
            return ai.content if isinstance(ai.content, str) else str(ai.content)
        except Exception:
            return ""

    def _system_prompt(self, spec: PhaseSpec, context: str, research: str,
                       repo: str = "", docs: str = "", seed: str = "") -> str:
        parts = [
            f"You are a {spec.role} helping an experienced developer design a software "
            f"project, one SDLC phase at a time. This phase: {spec.title}.",
            f"Project idea: {self.state.get('idea') or '(see prior decisions)'}",
            f"Your goal: {spec.goal} Specifically decide: {spec.focus}.",
            "Be concrete and SENIOR: address the genuinely hard, defining parts of THIS "
            "specific product — not generic boilerplate. Name specific technologies, "
            "protocols, patterns, and current stable versions. Cover ALL of the requested "
            "scope; do not silently defer the hard features. Propose a clear recommendation "
            "with brief rationale, and ask focused questions only where you truly need the "
            "developer's decision. They are experienced — keep it tight but deep.",
        ]
        if spec.must_cover:
            parts += ["", "You MUST explicitly address each of these (skip one only if it "
                      "genuinely does not apply, and say why):",
                      *(f"- {item}" for item in spec.must_cover)]
        if repo:
            parts += ["", "# Existing codebase — build on and MATCH this (brownfield)", repo]
        if docs:
            parts += ["", "# Relevant project documents (e.g. an imported PRD/spec)", docs]
        if context:
            parts += ["", "# Decisions already made in earlier phases", context]
        if seed:
            parts += ["", f"# Inferred starting point for {spec.title} (confirm or adjust)", seed]
        if research:
            parts += ["", "# Current information from the web (use for versions/best practices)", research]
        return "\n".join(parts)

    def _research(self, spec: PhaseSpec) -> str:
        try:
            from rag.research import research_topic
            topic = f"{self.state.get('idea','')} {spec.title} best practices current versions 2026"
            return research_topic(topic, project="")["text"][:3000]
        except Exception:
            return ""

    def _discuss(self, spec: PhaseSpec) -> tuple[str, list]:
        context = self._prior_artifacts()
        research = self._research(spec) if spec.research else ""
        if spec.research:
            console.print("[dim]🌐 Researching current best practices…[/dim]")

        brownfield = self._has_existing_code()
        repo = self._repo_overview() if brownfield else ""
        docs = self._relevant_docs()
        seed = ""
        if spec.id == "conventions" and brownfield:
            console.print("[dim]🔎 Inferring conventions from your existing code…[/dim]")
            seed = self._infer_conventions()

        system = self._system_prompt(spec, context, research, repo, docs, seed)
        opening = (f"Open the {spec.title} phase: give a concise first-draft proposal for "
                   f"{spec.focus}, then ask me the key questions you need answered.")
        messages = [SystemMessage(content=system), HumanMessage(content=opening)]

        console.print(Rule(f"[bold magenta]{spec.role} — {spec.title}[/bold magenta]"))
        ai = _stream(messages)
        messages.append(AIMessage(content=ai))
        transcript = [f"**{spec.role}:** {ai}"]

        while True:
            console.print("\n[dim]Reply, or type: [bold]done[/bold] · [bold]skip[/bold] · "
                          "[bold]revise[/bold] · [bold]pause[/bold][/dim]")
            try:
                user = Prompt.ask(f"[bold yellow]{spec.id}[/bold yellow]").strip()
            except (EOFError, KeyboardInterrupt):
                return "pause", messages
            if not user:
                continue
            cmd = user.lower()
            if cmd in ("done", "d"):
                return "done", messages
            if cmd in ("skip", "s"):
                return "skip", messages
            if cmd in ("revise", "r"):
                return "revise", messages
            if cmd in ("pause", "p"):
                return "pause", messages
            messages.append(HumanMessage(content=user))
            transcript.append(f"**You:** {user}")
            ai = _stream(messages)
            messages.append(AIMessage(content=ai))
            transcript.append(f"**{spec.role}:** {ai}")
        # (unreachable) transcript joined by caller via _last_transcript

    _UNIT_DETAIL = {
        "entity": ("Design the **{item}** entity in full: every field with its type, the "
                   "primary key, foreign keys, indexes, relationships to other entities, and "
                   "constraints. If the project uses end-to-end encryption, store ciphertext "
                   "(never plaintext). Use ### for any sub-headings. Output clean Markdown for just this entity."),
        "resource": ("Design the **{item}** API in full: every endpoint (HTTP method + path), "
                     "request and response shapes with field types, status codes, the error "
                     "format, the auth required, and any realtime/websocket events. Output "
                     "clean Markdown for just this resource."),
        "component": ("Detail the **{item}** component in full: its responsibilities, the "
                      "chosen technology and current stable version, its interfaces and "
                      "dependencies on other components, the data it owns, and how it scales. "
                      "Use ### for any sub-headings. Output clean Markdown for just this component."),
    }
    _UNIT_OVERVIEW = {
        "entity": ("Write the data-model OVERVIEW: an entity-relationship summary, the global "
                   "indexing strategy, and the migration approach."),
        "resource": ("Write the API OVERVIEW: base URL/versioning, the single consistent error "
                     "format, the auth scheme, the pagination convention, and the "
                     "realtime/websocket event model."),
        "component": ("Write the architecture OVERVIEW: the architecture style, how the "
                      "components fit together (the request/message flow), the data stores and "
                      "caches, and the cross-cutting concerns (the real-time backbone if "
                      "applicable)."),
    }

    def _summarize_decomposed(self, spec: PhaseSpec, messages: list, unit: str) -> str | None:
        """Design a heavy phase one unit at a time: list → detail each → assemble."""
        import json
        from core.model import balanced_json_arrays

        list_prompt = (
            f"Based on the requirements and this discussion, list the {unit}s to design for "
            f"the {spec.title}. Output ONLY a JSON array of short names in a sensible "
            f'dependency order, e.g. ["User", "Message"].'
        )
        raw = _stream(list(messages) + [HumanMessage(content=list_prompt)], precise=True)
        items: list[str] = []
        for span in balanced_json_arrays(raw):
            try:
                data = json.loads(span)
            except Exception:
                continue
            if isinstance(data, list):
                items = [str(x).strip() for x in data if isinstance(x, str) and x.strip()][:20]
                if items:
                    break
        if not items:
            return None  # fall back to the normal single-pass summarize

        console.print(f"[dim]🔬 Designing {len(items)} {unit}(s) one at a time: "
                      f"{', '.join(items)}[/dim]")
        sections = []
        overview = _stream(list(messages) + [HumanMessage(content=self._UNIT_OVERVIEW[unit])],
                           precise=True).strip()
        if overview:
            sections.append(f"## Overview\n\n{overview}")
        for item in items:
            console.print(Rule(f"[dim]{unit}: {item}[/dim]"))
            detail = _stream(
                list(messages) + [HumanMessage(content=self._UNIT_DETAIL[unit].format(item=item))],
                precise=True,
            ).strip()
            if detail:
                sections.append(f"## {item}\n\n{detail}")
        return "\n\n".join(sections) if sections else None

    def _summarize(self, spec: PhaseSpec, messages: list) -> str:
        from core.config import get_config

        if spec.decompose:
            decomposed = self._summarize_decomposed(spec, messages, spec.decompose)
            if decomposed:
                return decomposed   # decomposition is the quality mechanism here

        draft_prompt = (
            f"Summarize this {spec.title} discussion into a clean, structured Markdown "
            f"record of the DECISIONS made about: {spec.focus}. Use headings, bullets, and "
            f"tables where useful. This is the permanent spec for this phase — be precise "
            f"and complete, no fluff."
        )
        base = list(messages) + [HumanMessage(content=draft_prompt)]
        draft = _stream(base, precise=True).strip()

        if not draft or not get_config().get("devmode", "reflect", default=True):
            return draft

        # Reflection: a small model improves a concrete draft far better than it
        # writes a perfect one first-shot. One critique-and-revise pass.
        console.print(Rule("[dim]🔁 Refining the decision (critique + revise)…[/dim]"))
        improve_prompt = (
            f"Above is a DRAFT {spec.title} decision for: {self.state.get('idea', '')}.\n"
            f"As a senior {spec.role}, critique it and output an IMPROVED, complete version. "
            f"Specifically:\n"
            f"- Address the genuinely HARD, defining parts of THIS product that the draft "
            f"missed or treated generically.\n"
            f"- Name concrete technologies, protocols, patterns, and current stable versions.\n"
            f"- Ensure it fully covers: {spec.focus}, and is consistent with the requirements "
            f"and earlier decisions.\n"
            + ("".join(f"- It MUST explicitly cover: {item}\n" for item in spec.must_cover))
            + f"Output ONLY the improved decision in clean Markdown — no preamble."
        )
        improved = _stream(
            base + [AIMessage(content=draft), HumanMessage(content=improve_prompt)],
            precise=True,
        ).strip()
        return improved or draft

    # ── Phase runner ───────────────────────────────────────────────────────────

    def _run_review(self, spec: PhaseSpec) -> str:
        """The Design Reviewer critiques the other phases' decisions (no discussion)."""
        artifacts = self._prior_artifacts()
        if not artifacts.strip():
            console.print("[yellow]Nothing to review yet — run the design phases first.[/yellow]")
            return "skip"
        console.print(Rule(f"[bold magenta]{spec.role} — {spec.title}[/bold magenta]"))
        system = (
            f"You are a {spec.role} reviewing the design for an experienced developer. "
            f"Critically review the decisions below. Check: {spec.focus}. Output a concise "
            f"findings list — each finding with a severity (HIGH/MEDIUM/LOW), the phase it "
            f"concerns, and a concrete recommendation. Be direct; if it's solid, say so."
        )
        findings = _stream(
            [SystemMessage(content=system),
             HumanMessage(content=f"# Design decisions to review\n{artifacts[:8000]}\n\n"
                                  f"Produce the review findings.")],
            precise=True,
        )
        path = self._artifact_path(spec)
        path.parent.mkdir(parents=True, exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        path.write_text(f"# Design Review\n_Reviewed: {ts}_\n\n{findings.strip()}\n", encoding="utf-8")
        console.print(f"\n  [green]✔[/green] Review saved → "
                      f"[bold]{path.relative_to(self.workspace)}[/bold]")
        console.print("[dim]Address issues with 'dev revisit <phase>', then 'dev build'.[/dim]")
        return "done"

    def _run_phase(self, spec: PhaseSpec) -> str:
        if spec.kind == "review":
            return self._run_review(spec)
        while True:  # retry loop for 'revise'
            transcript_msgs: list = []
            result, messages = self._discuss(spec)
            if result in ("pause", "skip"):
                return result
            if result == "revise":
                console.print("[dim]Restarting this phase…[/dim]")
                continue
            # result == "done" → summarize + write artifact
            console.print(Rule("[dim]📝 Capturing decision…[/dim]"))
            decision = self._summarize(spec, messages)
            transcript = "\n\n".join(
                (f"**You:** {m.content}" if isinstance(m, HumanMessage) else f"**{spec.role}:** {m.content}")
                for m in messages[2:]  # skip system + opening
            )
            path = self._write_artifact(spec, decision, transcript)
            console.print(f"  [green]✔[/green] Saved → [bold]{path.relative_to(self.workspace)}[/bold]")
            return "done"

    # ── Public ─────────────────────────────────────────────────────────────────

    def show_status(self) -> None:
        lines = []
        for p in PHASES:
            st = self.state["phases"].get(p.id, {}).get("status", "pending")
            lines.append(f"  {_STATUS_ICON.get(st, '○')}  {p.title}")
        console.print(Panel("\n".join(lines),
                            title=f"[bold magenta]🧭 Developer Mode — {self.state.get('idea','')[:50]}[/bold magenta]",
                            subtitle="[dim]docs/dev/[/dim]", border_style="magenta"))

    def _build_exists(self) -> bool:
        bp = self.dir / "build_plan.json"
        if not bp.exists():
            return False
        try:
            plan = json.loads(bp.read_text(encoding="utf-8"))
            return any(f.get("status") == "done" for f in plan.get("files", []))
        except Exception:
            return False

    def revisit(self, phase_id: str) -> None:
        """Re-run one phase to change its decision, then auto-resync the code if it changed."""
        spec = PHASES_BY_ID.get(phase_id)
        if not spec:
            console.print(f"[yellow]Unknown phase '{phase_id}'. Phases: "
                          f"{', '.join(PHASES_BY_ID)}[/yellow]")
            return

        old_path = self._artifact_path(spec)
        old = old_path.read_text(encoding="utf-8", errors="replace") if old_path.exists() else ""

        console.print(Rule(f"[bold]Revisiting: {spec.title}[/bold]"))
        self._set_status(spec.id, "in_progress")
        result = self._run_phase(spec)
        self._set_status(spec.id, "done" if result == "done"
                         else ("pending" if result == "pause" else "skipped"))
        if result != "done":
            return

        new = old_path.read_text(encoding="utf-8", errors="replace") if old_path.exists() else ""
        if not old or not self._build_exists():
            return

        old_dec, new_dec = _decision_section(old), _decision_section(new)
        if old_dec.strip() == new_dec.strip():
            console.print("[dim]Decision unchanged — no resync needed.[/dim]")
            return

        console.print()
        if Confirm.ask(f"The {spec.title} decision changed. Auto-resync the code to match?",
                       default=True):
            from devmode.resync import resync
            resync(self.workspace, spec.title, old_dec, new_dec)

    def run(self, resume: bool = False, only: str | None = None) -> None:
        if not self.state.get("idea") and not resume:
            console.print("[yellow]No idea set. Use: develop <your idea>[/yellow]")
            return
        self._save()
        self.show_status()

        specs = [PHASES_BY_ID[only]] if only and only in PHASES_BY_ID else PHASES
        for spec in specs:
            st = self.state["phases"][spec.id]["status"]
            if st == "done" and not only:
                continue
            console.print()
            if st != "in_progress" and not Confirm.ask(
                f"[bold]Run phase: {spec.title}?[/bold] [dim]({spec.role})[/dim]", default=True
            ):
                self._set_status(spec.id, "skipped")
                continue
            self._set_status(spec.id, "in_progress")
            result = self._run_phase(spec)
            if result == "pause":
                console.print("\n[yellow]Paused. Resume with [bold]dev resume[/bold].[/yellow]")
                self._set_status(spec.id, "pending")
                return
            self._set_status(spec.id, "skipped" if result == "skip" else "done")
            self.show_status()

        console.print()
        console.print(Panel(
            "🎉 Design phases complete.\n\n"
            "[dim]Artifacts are in docs/dev/ and conventions in AICODER.md — edit them "
            "anytime. Next: the build hand-off (coming next).[/dim]",
            title="[bold green]Developer Mode — design done[/bold green]", border_style="green"))
